import { Book } from "./book.model";
import { v4 as uuid } from "uuid";

export const INITIAL_BOOKS: Book[] = [
  {
    id: uuid(),
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publishedYear: 1925,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "1984",
    author: "George Orwell",
    publishedYear: 1949,
    genre: "Dystopian",
  },
  {
    id: uuid(),
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publishedYear: 1960,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publishedYear: 1813,
    genre: "Romance",
  },
  {
    id: uuid(),
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publishedYear: 1951,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "Brave New World",
    author: "Aldous Huxley",
    publishedYear: 1932,
    genre: "Dystopian",
  },
  {
    id: uuid(),
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publishedYear: 1937,
    genre: "Fantasy",
  },
  {
    id: uuid(),
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    publishedYear: 1847,
    genre: "Romance",
  },
  {
    id: uuid(),
    title: "Animal Farm",
    author: "George Orwell",
    publishedYear: 1945,
    genre: "Satire",
  },
  {
    id: uuid(),
    title: "Lord of the Flies",
    author: "William Golding",
    publishedYear: 1954,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "The Odyssey",
    author: "Homer",
    publishedYear: -800,
    genre: "Epic",
  },
  {
    id: uuid(),
    title: "Moby-Dick",
    author: "Herman Melville",
    publishedYear: 1851,
    genre: "Adventure",
  },
  {
    id: uuid(),
    title: "Frankenstein",
    author: "Mary Shelley",
    publishedYear: 1818,
    genre: "Gothic",
  },
  {
    id: uuid(),
    title: "Wuthering Heights",
    author: "Emily Brontë",
    publishedYear: 1847,
    genre: "Romance",
  },
  {
    id: uuid(),
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    publishedYear: 1939,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "Catch-22",
    author: "Joseph Heller",
    publishedYear: 1961,
    genre: "Satire",
  },
  {
    id: uuid(),
    title: "The Stranger",
    author: "Albert Camus",
    publishedYear: 1942,
    genre: "Philosophical",
  },
  {
    id: uuid(),
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    publishedYear: 1969,
    genre: "Science Fiction",
  },
  {
    id: uuid(),
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    publishedYear: 1850,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    publishedYear: 1953,
    genre: "Dystopian",
  },
  {
    id: uuid(),
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    publishedYear: 1890,
    genre: "Gothic",
  },
  {
    id: uuid(),
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    publishedYear: 1967,
    genre: "Magical Realism",
  },
  {
    id: uuid(),
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    publishedYear: 1952,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    publishedYear: 1866,
    genre: "Philosophical",
  },
  {
    id: uuid(),
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    publishedYear: 1880,
    genre: "Philosophical",
  },
  {
    id: uuid(),
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    publishedYear: 1859,
    genre: "Historical",
  },
  {
    id: uuid(),
    title: "The Bell Jar",
    author: "Sylvia Plath",
    publishedYear: 1963,
    genre: "Semi-Autobiographical",
  },
  {
    id: uuid(),
    title: "Dune",
    author: "Frank Herbert",
    publishedYear: 1965,
    genre: "Science Fiction",
  },
  {
    id: uuid(),
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    publishedYear: 1985,
    genre: "Dystopian",
  },
  {
    id: uuid(),
    title: "Beloved",
    author: "Toni Morrison",
    publishedYear: 1987,
    genre: "Historical",
  },
  {
    id: uuid(),
    title: "The Road",
    author: "Cormac McCarthy",
    publishedYear: 2006,
    genre: "Post-Apocalyptic",
  },
  {
    id: uuid(),
    title: "The Alchemist",
    author: "Paulo Coelho",
    publishedYear: 1988,
    genre: "Philosophical",
  },
  {
    id: uuid(),
    title: "Siddhartha",
    author: "Hermann Hesse",
    publishedYear: 1922,
    genre: "Philosophical",
  },
  {
    id: uuid(),
    title: "The Metamorphosis",
    author: "Franz Kafka",
    publishedYear: 1915,
    genre: "Absurdist",
  },
  {
    id: uuid(),
    title: "Lolita",
    author: "Vladimir Nabokov",
    publishedYear: 1955,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "The Color Purple",
    author: "Alice Walker",
    publishedYear: 1982,
    genre: "Historical",
  },
  {
    id: uuid(),
    title: "Invisible Man",
    author: "Ralph Ellison",
    publishedYear: 1952,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "The Sun Also Rises",
    author: "Ernest Hemingway",
    publishedYear: 1926,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "A Clockwork Orange",
    author: "Anthony Burgess",
    publishedYear: 1962,
    genre: "Dystopian",
  },
  {
    id: uuid(),
    title: "The Trial",
    author: "Franz Kafka",
    publishedYear: 1925,
    genre: "Absurdist",
  },
  {
    id: uuid(),
    title: "The Name of the Rose",
    author: "Umberto Eco",
    publishedYear: 1980,
    genre: "Historical Mystery",
  },
  {
    id: uuid(),
    title: "The Sound and the Fury",
    author: "William Faulkner",
    publishedYear: 1929,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "Their Eyes Were Watching God",
    author: "Zora Neale Hurston",
    publishedYear: 1937,
    genre: "Classic",
  },
  {
    id: uuid(),
    title: "The Outsiders",
    author: "S.E. Hinton",
    publishedYear: 1967,
    genre: "Young Adult",
  },
  {
    id: uuid(),
    title: "Charlotte's Web",
    author: "E.B. White",
    publishedYear: 1952,
    genre: "Children's",
  },
  {
    id: uuid(),
    title: "The Giver",
    author: "Lois Lowry",
    publishedYear: 1993,
    genre: "Young Adult",
  },
  {
    id: uuid(),
    title: "Neuromancer",
    author: "William Gibson",
    publishedYear: 1984,
    genre: "Cyberpunk",
  },
  {
    id: uuid(),
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    publishedYear: 1911,
    genre: "Children's",
  },
  {
    id: uuid(),
    title: "Ender's Game",
    author: "Orson Scott Card",
    publishedYear: 1985,
    genre: "Science Fiction",
  },
  {
    id: uuid(),
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    publishedYear: 1950,
    genre: "Fantasy",
  },
];